### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2026' in position 139: character maps to <undefined>

### ISSUE THREAD

**Issue by baditaflorin** [llSourcell/twitter_sentiment_challenge#1]
C:\LEARN PYTHON\sirajology\twitter_sentiment_challenge>python demo.py
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    print(tweet.text)
  File "C:\Python27\lib\encodings\cp852.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2026' in position 139: character maps to <undefined>

**Comment by prisar** [comment]
run `chcp 65001` at first.

**steps:**

1.  `chcp 65001`

2. `python demo.py`

**Comment by ravindukaluarachchi** [comment]
encode the text when printing

print(tweet.text.encode("utf-8"))

**Comment by hygull** [comment]
@ravindukaluarachchi suggested good.

It works fine.

```python
public_tweets = api.home_timeline()
for tweet in public_tweets:
    # print(tweet.text);
    print ((tweet.text).encode('utf8')) 
```

**Comment by kevenex** [comment]
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 44-44: Non-BMP character not supported in Tk

Getting this error

**Comment by hygull** [comment]
> UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 44-44: Non-BMP character not supported in Tk
> 
> Getting this error

Can you check https://stackoverflow.com/questions/32442608/ucs-2-codec-cant-encode-characters-in-position-1050-1050 if this is useful.

**Comment by sahar99** [comment]
> encode the text when printing
> 
> print(tweet.text.encode("utf-8"))

what if the print statement hold  jason not a text? it didn't work like this print(status._json.encode("utf-8"))

**Comment by toktok911** [comment]
> > encode the text when printing
> > print(tweet.text.encode("utf-8"))
> 
> what if the print statement hold jason not a text? it didn't work like this print(status._json.encode("utf-8"))

Then simply dont print the json output (the returned tweets) to the console and avoid that as much as possible. 
Instead, write those returned tweets of a json format into a text file for example using a for loop and the write methods of Python, so that you can examine the json output later.
If you, however, tried redirecting the console output to a text file using something like: 
python tweets2000.py > output200.txt , it may still prompt the encoding error.

**Comment by ghost** [comment]
Well the problem is not with python actually , I was getting  a similar  I did a simple fix in windows there is a way you can set the defaulting encoding to utf-8 like I did but this feature is only available as a beta in win 10 but it resolved the error for me

so the way to test if python renders the problematic character in python is to just enter interactive mode in python and just print('xxxxx') my bet is it will another thing is I am using vs code as my ide which sets the encoding to utf-8 for python  by default 

Hope that helps

**Comment by RAJANAGORI** [comment]
> run `chcp 65001` at first.
> 
> **steps:**
> 
> 1. `chcp 65001`
> 2. `python demo.py`

Thanks.....for kick-ass solution dude

**Comment by yasinaziz** [comment]
![image](https://user-images.githubusercontent.com/34503256/62480266-ef30fb00-b7e1-11e9-9677-87054adf8bff.png)

**Comment by yasinaziz** [comment]
![image](https://user-images.githubusercontent.com/34503256/62480307-0a9c0600-b7e2-11e9-9129-856d5d379278.png)

**Comment by yasinaziz** [comment]
any1 can help to finish it

**Comment by sangi2504** [comment]
Hi Yasinaziz, May I please know if you managed to resolve the issue. Your assistance will be of greater help. Thanks

**Comment by BhargavRajyagor** [comment]
Please hep me to solve this

 '  File "C:\\ProgramData\\Anaconda3\\lib\\encodings\\cp1252.py", line 19, in encode',
 '    return codecs.charmap_encode(input,self.errors,encoding_table)[0]',
 "UnicodeEncodeError: 'charmap' codec can't encode character '\\x87' in position 39: character maps to <undefined>"]


Thanks

**Comment by yesdeepakmittal** [comment]
import io
file = io.open('twitter.csv', "w", encoding="utf-8")

**Comment by shraddhap238** [comment]
> encode the text when printing
> 
> print(tweet.text.encode("utf-8"))

thank u so much I was getting this problem from 2 days I was not able to solve it but after trying your solution it worked thanks a lot

**Comment by me-suzy** [comment]
```
# READ

def read_text_from_file(file_path):
    """
    This function returns the content of a file.
     file_path: the path to the file you want to read from
    """
    with open(file_path, encoding='utf8') as f:
        text = f.read()
        return text

# WRITE

def write_to_file(text, file_path, encoding='utf8'):
    """
    This function writes a text to a file.
     text: the text you want to write
     file_path: the path to the file you want to write to
    """
    with open(file_path, 'wb') as f:
        f.write(text.encode('utf-8', 'ignore'))

```

**Comment by hafedh-hichri** [comment]
i just had the save problem rn in my `GIT BASH` 
the reason behind me getting this error is because i am using themes in my terminal


![image](https://user-images.githubusercontent.com/70411813/197409220-88fbaaa5-ab3f-4680-a90a-6337ff596b0e.png)


the easiest fix i can think of is disabling `oh-my-push` theme that i was using 
first open `.bash_profile` which you can find in `C:\Users\<username here>` and remove the line that says `eval "$(oh-my-posh --init --shell bash --config ~/my-profile.omp.json)" ` or just comment it out 
and your `git bash` should go back to normal 


![image](https://user-images.githubusercontent.com/70411813/197409393-9f4c6b77-36b8-4ba0-91d6-473e1465db11.png)

**Comment by sabbir2609** [comment]
> chcp 65001

same problem

**Comment by s-ali-mi** [comment]
open('test.txt', 'w+', encoding="utf-8")

**Comment by ghirati** [comment]
with open('example.txt', '(r/ w / a)', encoding='utf-8') as f:

**Comment by evansmbithi** [comment]
Since Python 3.7 you can change the encoding of standard streams with reconfigure()
import sys
sys.stdout.reconfigure(encoding='utf-8') 

confirm whether encoding has changed from cp1252 to utf-8
print(sys.stdout.encoding)
